//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article
    {
        public long Id { get; set; }
        public string Title { get; set; }
        public string Alias { get; set; }
        public string Introtext { get; set; }
        public string Fulltext { get; set; }
        public System.DateTime Date { get; set; }
        public System.DateTime DatePublished { get; set; }
        public System.DateTime DatePullback { get; set; }
        public System.DateTime DateLastmod { get; set; }
        public long Hits { get; set; }
        public int ModificationsCount { get; set; }
        public int Published { get; set; }
        public long Level { get; set; }
    
        public virtual ICollection<ArticleAuthor> ArticleAuthor { get; set; }
        public virtual ICollection<ArticlesCategories> ArticleCategory { get; set; }
        public virtual Role Role { get; set; }
        public virtual ICollection<comments> Comment { get; set; }
        public virtual ICollection<menuitems> Menuitem { get; set; }
        public virtual ICollection<tags_articles> TagArticle { get; set; }
    }
}
