//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Author
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public string Lastname { get; set; }
        public long UserId { get; set; }
        public string Description { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual ICollection<ArticleAuthor> ArticleAuthor { get; set; }
        public virtual User User { get; set; }
    }
}
