//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public long Id { get; set; }
        public long NameTextId { get; set; }
        public Nullable<long> ParentId { get; set; }
        public long TextTextId { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<long> CarouselTextId { get; set; }
    
        public virtual ICollection<ArticleCategory> ArticleCategory { get; set; }
        public virtual ICollection<Category> Children { get; set; }
        public virtual Category Parent { get; set; }
        public virtual Text NameText { get; set; }
        public virtual Text TextText { get; set; }
        public virtual Text CarouselText { get; set; }
        public virtual ICollection<MenuItem> MenuItems { get; set; }
        public virtual ICollection<Product> Product { get; set; }
    }
}
