//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentGroup
    {
        public long Id { get; set; }
    
        public virtual ICollection<Document> Documents { get; set; }
        public virtual ICollection<Product> Products { get; set; }
    }
}
