//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public long id { get; set; }
        public Nullable<long> name_text_id { get; set; }
        public string path { get; set; }
        public Nullable<long> docgroup_id { get; set; }
    
        public virtual DocumentGroup DocumentGroup { get; set; }
        public virtual Text Text { get; set; }
    }
}
