//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public long Id { get; set; }
        public long Title { get; set; }
        public long ShortDescriptionTextId { get; set; }
        public long TextTextId { get; set; }
        public byte[] date { get; set; }
        public Nullable<long> image_id { get; set; }
        public Nullable<long> product_id { get; set; }
        public Nullable<System.DateTime> date_order { get; set; }
    
        public virtual Image Image { get; set; }
        public virtual Product Product { get; set; }
        public virtual Text TitleText { get; set; }
        public virtual Text ShortDescriptionText { get; set; }
        public virtual Text TextText { get; set; }
    }
}
