//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Page
    {
        public long Id { get; set; }
        public long TitleTextId { get; set; }
        public long TextTextId { get; set; }
    
        public virtual Text TitleText { get; set; }
        public virtual Text TextText { get; set; }
    }
}
