//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public long Id { get; set; }
        public long TitleTextId { get; set; }
        public long SubtitleTextId { get; set; }
        public long DescriptionTextId { get; set; }
        public long TextTextId { get; set; }
        public Nullable<long> ImageId { get; set; }
    
        public virtual Image Image { get; set; }
        public virtual ICollection<News> News { get; set; }
        public virtual Text TitleText { get; set; }
        public virtual Text SubtitleText { get; set; }
        public virtual Text DescriptionText { get; set; }
        public virtual Text TextText { get; set; }
        public virtual ICollection<DocumentGroup> DocumentGroups { get; set; }
        public virtual ICollection<Image> Images { get; set; }
        public virtual ICollection<Category> Categories { get; set; }
        public virtual ICollection<Product> Similar { get; set; }
        public virtual ICollection<Product> SimilarTo { get; set; }
    }
}
