//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<long> ParentId { get; set; }
    
        public virtual ICollection<Article> Articles { get; set; }
        public virtual ICollection<RoleResource> RoleResources { get; set; }
        public virtual ICollection<Role> Children { get; set; }
        public virtual Role Parent { get; set; }
        public virtual ICollection<User> User { get; set; }
    }
}
