//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TextValue
    {
        public long id { get; set; }
        public string culture { get; set; }
        public string value { get; set; }
        public long text_id { get; set; }
        public string seo_value { get; set; }
    
        public virtual Text Text { get; set; }
    }
}
